export { default as Header } from "./sections/Header";
export { default as Footer } from "./sections/Footer";
export { default as Hero } from "./sections/Hero";
export { default as About } from "./sections/About";
export { default as Experience } from "./sections/Experiance";
export { default as Skills } from "./sections/Skills";
export { default as WorkProjects } from "./sections/work/WorkProjects";
export { default as Contact } from "./sections/Contact";
export { default as PersonalProjects } from "./sections/PerosnalProjects";
